version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./news-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:9000
    networks:
      - news-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./news-backend:/var/www/html
    environment:
      - APP_ENV=development
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=news_hub
      - DB_USERNAME=news_user
      - DB_PASSWORD=news_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - news-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=news_hub
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - news-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - news-network

networks:
  news-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: